# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutapp', '0028_auto_20180914_1516'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='labelledata',
            index=models.Index(fields=['Field'], name='scoutapp_la_Field_9b3952_idx'),
        ),
    ]
