# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutapp', '0029_auto_20180917_1730'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='labelledata',
            index=models.Index(fields=['Date', 'Field'], name='scoutapp_la_Date_273153_idx'),
        ),
    ]
